on:
  push:
    branches:
      - demo
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 5.9.37.15
          username: ${{ secrets.ftp_username_demo }}
          password: ${{ secrets.ftp_password_demo }}
          server-dir: /bp1.yiii.ir/
